<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>إضافة محل جديد - لوحة التحكم</title>
                <script src="https://cdn.tailwindcss.com"></script>
                    <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;700;800&display=swap" rel="stylesheet">
                        <style> body { font-family: 'Tajawal', sans-serif; } </style>
                        </head>
                        <body class="bg-slate-100 min-h-screen py-10 px-4">

                            <div class="max-w-xl mx-auto bg-white p-8 rounded-3xl shadow-sm border border-slate-200">
                                    
                                            <div class="flex items-center justify-between mb-6 pb-4 border-b">
                                                        <h1 class="text-xl font-bold text-slate-800">➕ إضافة محل / مؤسسة جديدة</h1>
                                                                    <a href="{{ route('admin.dashboard') }}" class="text-xs font-bold text-slate-500 hover:text-slate-800">← رجوع للوحة التحكم</a>
                                                                            </div>

                                                                                    @if($errors->any())
                                                                                                <div class="bg-red-50 text-red-700 p-3 rounded-xl mb-4 text-xs font-bold border border-red-200">
                                                                                                                يرجى التأكد من تعبئة الحقول المطلوبة بشكل صحيح.
                                                                                                                            </div>
                                                                                                                                    @endif

                                                                                                                                            <form action="{{ route('shops.store') }}" method="POST" class="space-y-4">
                                                                                                                                                        @csrf

                                                                                                                                                                    <div>
                                                                                                                                                                                    <label class="block text-xs font-bold text-slate-700 mb-1">اسم المحل / المؤسسة:</label>
                                                                                                                                                                                                    <input type="text" name="name" value="{{ old('name') }}" placeholder="مثال: مطعم السلام" required class="w-full text-sm p-3 rounded-xl border border-slate-300 focus:outline-none focus:border-indigo-600">
                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                            <label class="block text-xs font-bold text-slate-700 mb-1">نسبة الخصم (%):</label>
                                                                                                                                                                                                                                                            <input type="number" step="0.1" name="discount" value="{{ old('discount') }}" placeholder="مثال: 15" required class="w-full text-sm p-3 rounded-xl border border-slate-300 focus:outline-none focus:border-indigo-600">
                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                    <label class="block text-xs font-bold text-slate-700 mb-1">العنوان / الفرع:</label>
                                                                                                                                                                                                                                                                                                                    <input type="text" name="address" value="{{ old('address') }}" placeholder="مثال: غزة - الرمال" required class="w-full text-sm p-3 rounded-xl border border-slate-300 focus:outline-none focus:border-indigo-600">
                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                            <label class="block text-xs font-bold text-slate-700 mb-1">تفاصيل الخصم (اختياري):</label>
                                                                                                                                                                                                                                                                                                                                                                            <textarea name="details" rows="3" placeholder="مثال: الخصم يشمل كافة الوجبات العائلية" class="w-full text-sm p-3 rounded-xl border border-slate-300 focus:outline-none focus:border-indigo-600">{{ old('details') }}</textarea>
                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                    <div class="pt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-xl transition shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                        💾 حفظ وإضافة المحل
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>